<?php

it('adds fields for generated filament form schemas', function () {
    $basePath = dirname(__DIR__, 2);
    $schemas = [
        'app/Filament/Resources/ActivityLogs/Schemas/ActivityLogForm.php' => [
            'user_id',
            'action',
            'ip_address',
            'user_agent',
            'properties',
        ],
        'app/Filament/Resources/CartItems/Schemas/CartItemForm.php' => [
            'cart_id',
            'product_id',
            'product_seller_id',
            'quantity',
            'price',
        ],
        'app/Filament/Resources/Carts/Schemas/CartForm.php' => [
            'user_id',
        ],
        'app/Filament/Resources/Commissions/Schemas/CommissionForm.php' => [
            'vendor_id',
            'order_item_id',
            'commission_rate',
            'commission_amount',
            'net_amount',
            'status',
        ],
        'app/Filament/Resources/Disputes/Schemas/DisputeForm.php' => [
            'order_item_id',
            'user_id',
            'vendor_id',
            'reason',
            'status',
        ],
        'app/Filament/Resources/Favorites/Schemas/FavoriteForm.php' => [
            'user_id',
            'product_id',
        ],
        'app/Filament/Resources/Notifications/Schemas/NotificationForm.php' => [
            'user_id',
            'order_id',
            'shipment_id',
            'type',
            'channel',
            'title',
            'message',
            'data',
            'sent_at',
            'read_at',
        ],
        'app/Filament/Resources/OrderItems/Schemas/OrderItemForm.php' => [
            'order_id',
            'vendor_id',
            'product_id',
            'quantity',
            'price',
            'status',
        ],
        'app/Filament/Resources/Orders/Schemas/OrderForm.php' => [
            'user_id',
            'order_number',
            'total_price',
            'status',
            'payment_method',
        ],
        'app/Filament/Resources/Payments/Schemas/PaymentForm.php' => [
            'order_id',
            'user_id',
            'amount',
            'payment_provider',
            'payment_type',
            'status',
            'transaction_id',
            'paid_at',
        ],
        'app/Filament/Resources/PriceHistories/Schemas/PriceHistoryForm.php' => [
            'variant_id',
            'price',
            'sale_price',
        ],
        'app/Filament/Resources/RecentlyVieweds/Schemas/RecentlyViewedForm.php' => [
            'user_id',
            'product_id',
            'viewed_at',
        ],
        'app/Filament/Resources/Refunds/Schemas/RefundForm.php' => [
            'order_item_id',
            'user_id',
            'vendor_id',
            'reason',
            'status',
            'refund_amount',
        ],
        'app/Filament/Resources/SearchIndices/Schemas/SearchIndexForm.php' => [
            'entity_type',
            'entity_id',
            'searchable_text',
        ],
        'app/Filament/Resources/SearchLogs/Schemas/SearchLogForm.php' => [
            'user_id',
            'query',
            'results_count',
        ],
        'app/Filament/Resources/Translations/Schemas/TranslationForm.php' => [
            'entity_type',
            'entity_id',
            'locale',
            'field',
            'value',
        ],
        'app/Filament/Resources/VendorBalances/Schemas/VendorBalanceForm.php' => [
            'vendor_id',
            'balance',
            'pending_balance',
            'last_settlement_at',
        ],
        'app/Filament/Resources/VendorPayouts/Schemas/VendorPayoutForm.php' => [
            'vendor_id',
            'amount',
            'payout_method',
            'status',
            'period_start',
            'period_end',
            'paid_at',
        ],
        'app/Filament/Resources/VendorPenalties/Schemas/VendorPenaltyForm.php' => [
            'vendor_id',
            'reason',
            'penalty_points',
            'expires_at',
        ],
        'app/Filament/Resources/VendorPerformanceLogs/Schemas/VendorPerformanceLogForm.php' => [
            'vendor_id',
            'metric',
            'value',
            'logged_at',
        ],
        'app/Filament/Resources/VendorScores/Schemas/VendorScoreForm.php' => [
            'vendor_id',
            'total_score',
            'delivery_score',
            'rating_score',
            'stock_score',
            'support_score',
        ],
        'app/Filament/Resources/VendorTiers/Schemas/VendorTierForm.php' => [
            'name',
            'min_total_orders',
            'min_rating',
            'max_cancel_rate',
            'max_return_rate',
            'priority_boost',
            'badge_icon',
        ],
        'app/Filament/Resources/PriceAlerts/Schemas/PriceAlertForm.php' => [
            'user_id',
            'product_id',
            'target_price',
            'is_active',
            'notified_at',
        ],
        'app/Filament/Resources/StockAlerts/Schemas/StockAlertForm.php' => [
            'user_id',
            'product_id',
            'is_active',
            'notified_at',
        ],
        'app/Filament/Resources/NotificationSettings/Schemas/NotificationSettingForm.php' => [
            'user_id',
            'email_campaigns',
            'email_orders',
            'email_promotions',
            'email_reviews',
            'sms_campaigns',
            'sms_orders',
            'sms_promotions',
            'push_enabled',
            'push_campaigns',
            'push_orders',
            'push_messages',
        ],
        'app/Filament/Resources/BlogPosts/Schemas/BlogPostForm.php' => [
            'user_id',
            'title',
            'slug',
            'excerpt',
            'content',
            'cover_image',
            'is_published',
            'published_at',
            'meta_title',
            'meta_description',
        ],
        'app/Filament/Resources/SearchHistories/Schemas/SearchHistoryForm.php' => [
            'user_id',
            'query',
            'results_count',
            'searched_at',
        ],
        'app/Filament/Resources/ReviewImages/Schemas/ReviewImageForm.php' => [
            'product_review_id',
            'image_path',
            'alt_text',
            'sort_order',
        ],
        'app/Filament/Resources/StaticPages/Schemas/StaticPageForm.php' => [
            'title',
            'slug',
            'content',
            'is_active',
            'meta_title',
            'meta_description',
        ],
        'app/Filament/Resources/CrispConversations/Schemas/CrispConversationForm.php' => [
            'session_id',
            'website_id',
            'nickname',
            'crisp_user_id',
            'user_id',
            'status',
            'last_message_at',
        ],
        'app/Filament/Resources/ContactMessages/Schemas/ContactMessageForm.php' => [
            'user_id',
            'name',
            'email',
            'phone',
            'subject',
            'message',
            'is_read',
            'replied_at',
        ],
    ];

    foreach ($schemas as $path => $columns) {
        $contents = file_get_contents($basePath.'/'.$path);

        foreach ($columns as $column) {
            expect($contents)->toContain("::make('{$column}')");
        }
    }
});
